### ISSUE TITLE
OI web app

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/OmicsIntegrator2#51]
Some notes from our convo on Friday, Mandy, as well as a few other things I just thought of. 

1. What is the mRNA input for? Colorization, or penalizing lowly expressed nodes? If the former, we run in to some consistency issues since we don’t use our entire proteomics file as our prize file. If the latter, we don’t have this functionality implemented, so maybe we should leave that box out for now. 
2. In the algorithm parameters, “Number of Trees” is a bit misleading, but I can’t think of a concise rewording. Maybe “connectivity”? Even that’s not ideal. 
3. Default for b should probably be in the range of 0-2, since we are no longer penalizing node prizes. Default 1 seems to work pretty good for me. 
4. Degree penalty (a) should now be edge penalty (g). Default 10 works fine for me. 
5. iRef14 also worked well for me, so maybe update that. 
6. Visualization: with new penalization scheme, high degree nodes are included, leading to outputs like the one below. Would it be too difficult to make non-robust edges transparent? Low robust edges could still be visualized, but at a very low visibility. 
7. Output for randomized experiments should auto return the top 400 robust nodes as a subnetwork, or some other heuristic. The former is already implemented in graph.py. 

![image](https://user-images.githubusercontent.com/7219365/31579533-445f3cd4-b106-11e7-931e-aea70501ee0c.png)

**Comment by AmandaKedaigle** [comment]
Just an update on this - I've done all the superficial updates. The web tool is running the latest version of OI2, with #2-5 on this list is updated. @iamjli I haven't been able to replicate your error with the mRNA file.

For reference, this is the code that is operating on the RNA file on the web tool:
`#RNA file - This needs to go last, since we only want RNA information on nodes that are already prizes
	if rnaf:
		for line in rnaf:
			words = line.strip().split('\t')
			if len(words) != 2:
				sys.exit('RNA file does not have two columns')
			name = words[0]
			try:
				logfc = float(words[1])
			except TypeError:
				sys.exit('Second column of RNA file should be a number')
			if name in prizes:
				if abs(prizes[name]['geneChange']) < abs(logfc):
					prizes[name]['geneChange'] = logfc
			else:
				continue
`

So it should only be adding geneChange attributes to nodes that are already terminals
