### ISSUE TITLE
Louvain clustering output

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/OmicsIntegrator2#69]
https://github.com/fraenkel-lab/OmicsIntegrator2/blob/11a24e1af254752137b911f4e013095d6652da49/src/graph.py#L366

Getting the following error: 
![image](https://user-images.githubusercontent.com/7219365/38847222-8a071f28-41ce-11e8-91f1-a178c93a94f0.png)

**Comment by iamjli** [comment]
If I comment this line out, the next line gives this error: 

![image](https://user-images.githubusercontent.com/7219365/38847259-bcd54aa6-41ce-11e8-9aa5-ee735e3b13ed.png)

**Comment by zfrenchee** [comment]
@iamjli unfortunately I can't support all branches of OI2.

* The first error suggests the python-louvain package is having trouble with networkx 2.0's new API. We were seeing this error a couple months ago and resolved it (I forget how) 
* The second error is because the subcellular localization data needs to be a pd.DataFrame, not a pd.Series now -- that's my bad, a miscommunication between myself and @brycehwang. It's fixed in master. 

I ran the example notebook in master and it works for me. Does it work for you?

**Comment by zfrenchee** [comment]
Closing (see #71)
